import { Router } from "express";
import { asyncHandler } from "../middleware/errorHandler";
import { env } from "../config/env";
import { cacheService } from "../services/cacheService";

/**
 * API information endpoint
 * Provsides basic information about the API for discovery and documentation
 */
export const infoRouter = Router();

infoRouter.get(
  "",
  asyncHandler(async (_req, res) => {
    res.json({
      name: "AegisCart API",
      version: env.APP_VERSION || "1.0.0",
      description: "Policy-first agentic commerce gateway for Razorpay test mode",
      timestamp: new Date().toISOString(),
      documentation: {
        openapi: "3.0.0",
        // In a real implementation, you would serve the OpenAPI spec here
        // For now, we provide a placeholder
        specUrl: "/api/v1/docs/openapi.json",
      },
      endpoints: {
        health: "/health",
        info: "/api/v1/info",
        // List of available API versions
        versions: ["v1"],
        // Example resources (would be generated from actual routes in a real spec)
        resources: [
          { name: "catalog", path: "/api/v1/catalog" },
          { name: "offers", path: "/api/v1/offers" },
          { name: "checkout", path: "/api/v1/checkout" },
          { name: "x402", path: "/api/v1/x402" },
          { name: "agent", path: "/api/v1/agent" },
          { name: "buyer", path: "/api/v1/buyer" },
        ],
      },
    });
  })
);

// Cache statistics endpoint for monitoring
infoRouter.get(
  "/cache/stats",
  asyncHandler(async (_req, res) => {
    const stats = cacheService.getStats();
    res.json({
      status: "ok",
      timestamp: new Date().toISOString(),
      cache: stats
    });
  })
);

// Placeholder for OpenAPI specification (would be generated by a tool like swagger-jsdoc in production)
infoRouter.get(
  "/docs/openapi.json",
  asyncHandler(async (_req, res) => {
    res.json({
      openapi: "3.0.0",
      info: {
        title: "AegisCart API",
        version: env.APP_VERSION || "1.0.0",
        description: "Policy-first agentic commerce gateway for Razorpay test mode",
      },
      servers: [
        {
          url: `http://localhost:${env.PORT}/api/v1`,
          description: "Development server",
        },
      ],
      paths: {}, // Would be populated with actual route definitions
      components: {
        schemas: {}, // Would be populated with shared schemas
      },
    });
  })
);