apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aegiscart-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # You can specify a storage class if needed
  # storageClassName: standard